#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"

  # Session
  [[blocks.segments]]
    type = "session"
    background = "#f09f26"
    foreground = "#f2f3f8"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = " {{ if .SSHSession }}\ueba9 {{ end }}{{ .UserName }} " # { if .SSHSession }}\ueba9 {{ end }}{{ .UserName }}@{{ .HostName }} "

  # Path
  [[blocks.segments]]
    type = "path"
    background = "#ff479c"
    foreground = "#ffffff"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \uf07b {{ .Path }} "
    [blocks.segments.properties]
      style = "folder"

  # Git
  [[blocks.segments]]
    type = "git"
    background = "#fffb38"
    background_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}", "{{ if gt .Ahead 0 }}#B388FF{{ end }}", "{{ if gt .Behind 0 }}#B388FF{{ end }}"]
    foreground = "#193549"
    leading_diamond = "\ue0b6"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
    trailing_diamond = "\ue0b4"
    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  # Running Environment START
  [[blocks.segments]]
    type = "node"
    background = "#6CA35E"
    foreground = "#ffffff"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = "go"
    background = "#8ED1F7"
    foreground = "#111111"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = "julia"
    background = "#4063D8"
    foreground = "#111111"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \ue624 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = "python"
    background = "#FFDE57"
    foreground = "#111111"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    [blocks.segments.properties]
      display_mode = "files"
      fetch_virtual_env = false

  [[blocks.segments]]
    type = "ruby"
    background = "#AE1401"
    foreground = "#ffffff"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    [blocks.segments.properties]
      display_mode = "files"
      fetch_version = true

  [[blocks.segments]]
    type = "azfunc"
    background = "#FEAC19"
    foreground = "#ffffff"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \uf0e7 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    [blocks.segments.properties]
      display_mode = "files"
      fetch_version = false

  [[blocks.segments]]
    type = "aws"
    background_templates = ["{{if contains \"default\" .Profile}}#FFA400{{end}}", "{{if contains \"jan\" .Profile}}#f1184c{{end}}"]
    foreground = "#ffffff"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    type = "root"
    background = "#ffff66"
    foreground = "#111111"
    powerline_symbol = "\ue0b0"
    style = "powerline"
    template = " \uf0ad "

  [[blocks.segments]]
    type = "docker"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#000000"
    background = "#0B59E7"
    template = "  {{ .Context }} "
  # Running Environment END

  # Shell
  [[blocks.segments]]
    type = "shell"
    style = "powerline"
    powerline_symbol = "\ue0b0"
    background = "#0077c2"
    foreground = "#ffffff"
    template = " \uf489 {{ .Name }} "

  # Status, Ending
  [[blocks.segments]]
    type = "status"
    background = "#00A676"
    background_templates = ["{{ if gt .Code 0 }}#f1184c{{ end }}"]
    foreground = "#ffffff"
    style = "diamond"
    template = " {{ if gt .Code 0 }}\uf00d {{ reason .Code }}{{ else }}\uf42e{{ end }} "
    trailing_diamond = "\ue0b4"
    [blocks.segments.properties]
      always_enabled = true

# Right
[[blocks]]
  alignment = "right"
  type = "prompt"

  [[blocks.segments]]
    type = "executiontime"
    style = "diamond"
    invert_powerline = true
    background = "#e4e4e4"
    foreground = "#585858"
    leading_diamond = "\ue0b6"
    trailing_diamond = "\ue0b0"
    template = "\ue641 {{ .FormattedMs }} "
    [blocks.segments.properties]
      always_enabled = true
      style = "austin"

  [[blocks.segments]]
    type = "time"
    style = "diamond"
    invert_powerline = true
    background = "#2e9599"
    foreground = "#111111"
    trailing_diamond = "\ue0b4"
    template = " {{ .CurrentDate | date .Format }}"

# Second Line, Prompt
[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"

  [[blocks.segments]]
    foreground = "#E06C75"
    style = "plain"
    template = ">"
    type = "text"

